# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 961a28b07ce5bbcf590118c6a80eba5c4c483d663ed3322a304d3b7042b99c436a0b3cf0894fa27066a23b0d33184577384b3ef8ce209aa35ab87e29f33f8a8b

test:
  secret_key_base: 9022572f774d1d7f639faca5d3dcd399eb417afedac32b36ff79c71f896039359694c75b5ae0f7873fe19c3041606a125aac19aa695a9357238847e4c00786d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
